export const answerPoolsByRound = {
  1: {
    strong: [
      "Give Vera the drumstick first.",
      "Let Vera have the drumstick and take the other piece.",
      "Pass Vera the drumstick first, then ask for one bite.",
      "Offer Vera the drumstick and act like he planned it all along.",
      "Let Vera have the drumstick, then claim the fries and drink.",
      "Give Vera the drumstick first and score some boyfriend points.",
      "Hand Vera the drumstick and remind her this is a sacrifice made out of love.",
      "Let Vera have the drumstick now and bring it up again next time she orders dessert.",
      "Give Vera the drumstick first and save himself the argument.",
      "Offer Vera the drumstick, then casually negotiate for something else in return.",
      "Let Vera have it and quietly accept that peace is more important than chicken.",
      "Give Vera the drumstick and hope she remembers this next time food is involved.",
    ],
    medium: [
      "Ask Vera if they can split it fairly.",
      "Play scissors paper stone for the drumstick.",
      "Offer to trade the drumstick for dessert rights.",
      "Ask Vera very politely if he can have it this once.",
      "Negotiate first instead of giving it away immediately.",
      "Take one bite each and call it even.",
      "Flip a coin and accept the result.",
      "Ask who wants it more before deciding.",
      "Trade the drumstick for a sip of her drink.",
      "See if Vera is willing to swap for another side.",
    ],
    weak: [
      "Eat it before Vera notices.",
      "Hide the drumstick under the mashed potato.",
      "Pretend there was never a drumstick.",
      "Ask KFC why only one drumstick came.",
      "Take the drumstick first and apologise later.",
      "Act blur and hope for the best.",
    ],
  },

  2: {
    strong: [
      "Vera should apologise first, then quickly go find an ATM.",
      "She should say sorry and immediately solve the payment problem.",
      "Vera should apologise and borrow cash from someone nearby if needed.",
      "She should own the mistake and find a way to pay before Shermann gets even angrier.",
      "Vera should apologise, then ask the stall uncle if they can hold the order while she withdraws cash.",
      "She should admit cashless failed today and go find cash fast.",
      "Vera should calm Shermann down first, then fix the payment issue immediately.",
      "She should say sorry, solve the food problem first, and argue about cashless later.",
      "Vera should apologise and ask a nearby friend or stranger for help if she has to.",
      "She should fix the problem first, then promise to carry emergency cash next time.",
      "Vera should take responsibility and make sure Shermann gets his chicken rice as soon as possible.",
      "She should stop defending the cashless idea for one minute and just solve it.",
    ],
    medium: [
      "Say sorry and go find an ATM.",
      "Borrow cash from someone nearby.",
      "Ask the stall if they can wait a bit.",
      "Offer to treat Shermann next time.",
      "Find another stall that takes card.",
      "Call a friend for help.",
      "Go to a convenience store and withdraw cash.",
      "Admit she was wrong and fix it.",
      "Ask if the stallholder can accept payment later.",
      "Try to find anyone nearby who has cash to spare.",
    ],
    weak: [
      "Tell Shermann to be patient and hungry.",
      "Ask him to survive on love alone.",
      "Pretend chicken rice was never the plan.",
      "Blame technology and stand there.",
      "Suggest skipping lunch.",
      "Smile and hope the payment systems magically come back.",
    ],
  },

  3: {
    strong: [
      "Stay on 15 and don’t draw.",
      "Hold at 15 and let the others take the risk.",
      "Stay and see how everyone else plays first.",
      "Keep the 15 and don’t risk busting.",
      "Stay on 15 and hope the others bust.",
      "Don’t draw — 15 is risky enough already.",
      "Stay on 15 and let the round play out.",
      "Hold and trust that drawing will make it worse.",
      "Stay and let the next players decide the outcome.",
      "Keep the 15 and accept whatever happens.",
      "Draw one more card and hope for a small number.",
      "Take the risk and hit once.",
      "Draw and trust luck instead of playing safe.",
      "Go for it and draw — 15 is not strong anyway.",
    ],
    medium: [
      "Stay on 15 and pray.",
      "Draw once and hope for the best.",
      "Hold and trust their luck.",
      "Take the safer option and stay.",
      "Go bold and draw.",
      "Let fate decide and hit once.",
      "Stay now and see whether the others bust first.",
      "Draw if they are feeling lucky.",
      "Don’t overthink it — just stay.",
      "Take one more card and hope it helps.",
    ],
    weak: [
      "Close eyes and draw.",
      "Say huat and hit.",
      "Ask the 财神爷 for help first.",
      "Draw because Chinese New Year is about taking risks.",
      "Stay and blame luck if it goes badly.",
      "Flip a coin and follow it.",
    ],
  },

  4: {
    strong: [
      "Vera should trade one episode of drama for one episode of Naruto.",
      "She should start with the most exciting episode so Shermann gets hooked first.",
      "Vera should pick a drama with faster pacing so he loses interest less quickly.",
      "She should bribe him with snacks while they watch.",
      "Vera should promise they only need to watch one episode first.",
      "She should stop at a cliffhanger so he wants to continue.",
      "Vera should tell Shermann this is romance training and he needs it.",
      "She should agree to watch something he likes after the drama.",
      "Vera should compare the male lead to an anime character Shermann likes.",
      "She should skip the slow beginning and show him the good parts first.",
      "Vera should make it feel like a deal instead of forcing him to sit through it.",
      "She should choose a shorter drama that is easier for him to finish.",
    ],
    medium: [
      "Offer snacks for every episode.",
      "Trade drama for anime.",
      "Start with a better drama.",
      "Skip to the good part first.",
      "Use a cliffhanger against him.",
      "Promise just one episode.",
      "Convince him it is romantic training.",
      "Watch his show after hers.",
      "Tell him the male lead is his competition.",
      "Make it a proper couple activity.",
    ],
    weak: [
      "Rename the male lead Naruto.",
      "Tell him there is fighting later.",
      "Hide the remote until he finishes the episode.",
      "Play the drama until he gives up resisting.",
      "Put on subtitles and hope that helps somehow.",
      "Tell him this counts as homework for marriage.",
    ],
  },

  5: {
    strong: [
      "He should tell her she does not need another keyboard, but help her choose anyway.",
      "Shermann should remind Vera she already has six keyboards, then ask which one she will actually use more.",
      "He should say she probably does not need keyboard number seven, but if she is buying one, choose the one she will enjoy using daily.",
      "He should ask Vera whether she cares more about how it looks or how it feels to type on.",
      "Shermann should gently question the need first, then help her compare the two properly.",
      "He should tell her the practical answer is no, but if the purchase is happening, pick the one she likes more.",
      "He should suggest choosing the keyboard she will still love after the excitement of buying wears off.",
      "Shermann should ask which keyboard solves a problem the other six do not.",
      "He should remind her she already has enough keyboards, then help her decide based on what matters more to her.",
      "He should say she does not need another one, but if she insists, choose the one she will regret least.",
      "Shermann should tell Vera to pick the one that will make her happiest every time she sits at her desk.",
      "He should answer carefully: be honest that she does not need it, but still be supportive.",
    ],
    medium: [
      "Ask which one she will actually use more.",
      "Say six is enough, but choose the prettier one.",
      "Say six is enough, but choose the better sounding one.",
      "Tell her to sell one before buying one.",
      "Ask whether this is a want or a need.",
      "Suggest waiting one week before buying.",
      "Tell her to pick the one she likes more.",
      "Tell her to follow her heart, but calmly.",
      "Ask which one sparks more joy.",
      "Say no first, then help anyway.",
    ],
    weak: [
      "Buy both and deal with it later.",
      "Pretend keyboards are an investment.",
      "Say the desk has room for one more.",
      "Tell her seven is a lucky number.",
      "Ask the keyboards which one wants to come home.",
      "Say this is clearly a serious business decision.",
    ],
  },
};

export const fallbackAnswers = [
  "Communicate honestly and keep the peace.",
  "Laugh it off and solve it together.",
  "Choose kindness first.",
  "Do the safer thing.",
  "Compromise a little.",
  "Pick peace over pride.",
  "Think long term.",
  "Stay calm and be smart.",
  "Say sorry quickly.",
  "Do not make it worse.",
];
