export const answerPoolsByRound = {
  1: {
    strong: [
      "Give Vera the drumstick first and earn boyfriend points.",
      "Offer Vera the drumstick and act like he was going to do that anyway.",
      "Say the drumstick is obviously hers and take the other piece with dignity.",
      "Pretend he prefers the other piece more and let Vera have the drumstick.",
      "Give Vera the drumstick first, then casually ask for one bite as tax.",
      "Tell Vera she can have the drumstick, but he gets the fries and drink.",
      "Split the peace, not the relationship — give Vera the drumstick.",
      "Let Vera take the drumstick and remind her this is a sacrifice made out of love.",
      "He should hand over the drumstick immediately before this becomes a bigger issue than it needs to be.",
      "He should let Vera have the drumstick, then make her remember this noble act the next time she orders dessert.",
      "Shermann should gracefully give Vera the drumstick and quietly tell himself that true love sometimes looks like eating the less exciting piece of chicken.",
      "He should offer Vera the drumstick without hesitation and turn it into a romantic moment, because KFC is temporary but peace is priceless.",
      "Give Vera the drumstick first, then say this is exactly the kind of sacrifice that should be remembered on anniversaries.",
      "Let Vera have the drumstick and cash in on the emotional credit later.",
      "He should surrender the drumstick now and win the long game.",
    ],
    medium: [
      "Ask if they can share it somehow.",
      "Rock-paper-scissors for the drumstick.",
      "Take one bite each and call it fair.",
      "Offer to swap for her next side dish.",
      "Ask Vera very politely if he can have it this once.",
      "Negotiate like adults over fried chicken.",
      "See who loves the drumstick more.",
      "Flip a coin and accept fate.",
      "Trade the drumstick for dessert rights.",
      "Settle it with one round of scissors paper stone.",
    ],
    weak: [
      "Eat fast before she notices.",
      "Hide the drumstick under the mashed potato.",
      "Close one eye and pretend there is no drumstick.",
      "Tell KFC to issue a refund for emotional damage.",
      "Chicken first, consequences later.",
      "Act blur and pray.",
    ],
  },

  2: {
    strong: [
      "Vera should apologise first, then quickly find a real solution before Shermann gets even hungrier.",
      "She should own it, admit that cashless failed today, and immediately ask nearby people if anyone can help break a note or lend some cash.",
      "Vera should apologise, then ask the stall uncle whether they can transfer the money later or hold the order while they go withdraw cash.",
      "She should stop defending cashless for one minute, apologise sincerely, and solve the problem before Shermann becomes impossible to deal with.",
      "Vera should admit she was wrong, calm Shermann down, and find the nearest ATM before anyone says something dramatic over chicken rice.",
      "She should apologise and suggest borrowing cash from a friend nearby, then repay them immediately once the payment systems are back.",
      "Vera should promise that from now on she will always carry a small emergency note, but first she needs to get Shermann fed.",
      "She should say sorry, solve the food problem first, and save the cashless debate for after they have eaten.",
      "Vera should apologise immediately and focus on finding any way to pay, because hungry people are not reasonable people.",
      "She should own the mistake and fix it fast, whether that means borrowing cash, finding an ATM, or begging the stallholder for mercy.",
      "Vera should stop trying to prove a point about cashless payments, admit defeat for the day, and make sure Shermann gets his chicken rice before the situation becomes a full-blown hunger meltdown.",
      "She should apologise properly, then go into problem-solving mode by finding an ATM, borrowing money, or asking the stallholder whether they can reserve the food for a few minutes.",
      "Vera should take responsibility, promise to keep emergency cash next time, and immediately do whatever is needed to make sure Shermann gets fed before he becomes even more annoyed.",
    ],
    medium: [
      "Say sorry and go find an ATM.",
      "Borrow cash from someone nearby.",
      "Ask the stall if they can wait a bit.",
      "Offer to treat him next time.",
      "Apologise before he says anything else.",
      "Find another stall that takes card.",
      "Call a friend for help.",
      "Look for a convenience store to withdraw cash.",
      "Admit she was wrong and fix it.",
      "Go solve it before he gets hangrier.",
    ],
    weak: [
      "Tell Shermann to enjoy the government's initiative.",
      "Ask him to survive on love alone.",
      "Pretend chicken rice was never the plan.",
      "Blame technology and stand there.",
      "Suggest fasting.",
      "Smile and hope for the best.",
    ],
  },

  3: {
    strong: [
      "They should play safe, stay on 15, and let the friends regret all their small-card decisions first.",
      "They should stop at 15 and trust that chaos will find the others instead.",
      "They should not get greedy, hold at 15, and let the pressure sit on everyone else.",
      "They should stay calm, stop at 15, and act confident even if they are panicking inside.",
      "They should hold, because Chinese New Year blackjack punishes greed and rewards dramatic self-control.",
      "They should stay on 15 and let luck decide the rest without helping it too much.",
      "They should pause, read the table, and avoid turning a decent hand into a disaster.",
      "They should stick with 15 and blame probability if things go wrong.",
      "They should stay, protect the hand, and let their friends take the bigger risks.",
      "They should hold and avoid becoming the couple who overthought their way into busting.",
      "They should stay on 15, keep a straight face, and let everyone else wonder whether they know something the rest of the table does not.",
      "They should resist the temptation to draw, because surviving Chinese New Year blackjack is often less about bravery and more about not doing anything reckless at the wrong moment.",
      "They should play it safe, hold at 15, and trust that the friends who drew low cards may have already changed the odds enough without Shermann and Vera making things worse for themselves.",
      "They should stop at 15 and fully commit to the power move of looking confident, even if internally both of them are already preparing excuses.",
    ],
    medium: [
      "Stay on 15 and pray.",
      "Draw only if they enjoy stress.",
      "Hold and trust the vibes.",
      "Take the risk together.",
      "Flip a coin and commit.",
      "Play safe this round.",
      "Stop now before they regret it.",
      "Draw for drama, stay for peace.",
      "Trust the lucky CNY energy.",
      "Let fate decide.",
    ],
    weak: [
      "Ask the 财神爷 for help.",
      "Close eyes and draw.",
      "Use couple telepathy.",
      "Panic together.",
      "Say huat and hit.",
      "Win first, think later.",
    ],
  },

  4: {
    strong: [
      "She should bargain with him: one episode of drama for one episode of Naruto.",
      "She should start with the juiciest episode first so he gets invested before he can escape.",
      "She should compare the male lead to an anime character he likes and slowly lure him in.",
      "She should make it a trade — if he finishes the drama, she will watch something he likes too.",
      "She should bribe him with snacks and emotional blackmail in equal measure.",
      "She should skip the slow beginning and show him the dramatic parts first so he has no choice but to care.",
      "She should explain that this is not just entertainment, this is romance training.",
      "She should promise him one short episode only, then trap him with a cliffhanger.",
      "She should watch the drama while sitting very close to him so leaving becomes socially difficult.",
      "She should tell him the male lead has more romantic skills than most real men and that this is an educational opportunity.",
      "Vera should ease him in gently by choosing a drama with faster pacing, strong chemistry, and enough plot to keep him curious before the romance lessons even begin.",
      "She should present the drama as a serious learning opportunity, then strategically pause at the most dramatic cliffhanger so Shermann is forced to wonder what happens next.",
      "She should turn it into a fair exchange by agreeing to watch something he likes too, because convincing someone to finish a drama is much easier when they feel like they are also getting a deal.",
      "She should start with the most exciting scenes first, keep the snacks flowing, and remind him that this is valuable training if he ever wants to compete with fictional male leads.",
      "She should cleverly describe the drama in a way that makes it sound like an emotional version of Naruto, then once he is invested it will be too late for him to escape.",
    ],
    medium: [
      "Offer snacks for every episode.",
      "Trade drama for anime.",
      "Start with a better drama.",
      "Skip to the good part first.",
      "Use cliffhangers against him.",
      "Promise just one episode.",
      "Convince him it is romantic training.",
      "Watch his show after yours.",
      "Tell him the male lead is his competition.",
      "Make it a couple activity.",
    ],
    weak: [
      "Rename the male lead Naruto.",
      "Play the drama at 2x speed.",
      "Tell him there is fighting later.",
      "Hide the remote.",
      "Force is a love language.",
      "Summon Talk no Jutsu.",
    ],
  },

  5: {
    strong: [
      "He should tell her both are nice, but six keyboards is already a full squad.",
      "He should gently remind her that she already has six and ask which problem this new one is actually solving.",
      "He should say the prettier one wins if she wants desk aesthetics, but only after asking why keyboard number seven is necessary.",
      "He should tell her she does not need another keyboard, but if she insists, at least choose the one she will enjoy using every day.",
      "He should respond carefully: first question the need, then help her choose without sounding unsupportive.",
      "He should say she definitely does not need another mechanical keyboard, but if this purchase is happening anyway, she should pick the one that makes her happiest.",
      "He should remind her that owning six keyboards already sounds like enough, then ask whether she wants beauty, sound, or just an excuse to buy another one.",
      "He should say, very calmly, that she does not need keyboard number seven — but if no one can stop this, she should choose the one she will regret least.",
      "He should answer honestly but gently, because this is one of those moments where the wrong tone matters more than the wrong keyboard.",
      "He should tell her she already has enough keyboards to start a small museum, but if she is still buying one, she should choose based on what she values more every day.",
      "Shermann should first remind Vera that six mechanical keyboards is already an impressive number for one person, then carefully guide her to choose based on whether she cares more about how it looks on the desk or how satisfying it feels to type on every day.",
      "He should say she definitely does not need another keyboard, but since this purchase clearly has strong emotional momentum already, she should choose the one that will make her happiest long after the excitement of buying it wears off.",
      "He should respond with extreme caution by gently pointing out that this is not a necessity, then helping her decide whether she wants something pretty to look at or something satisfying to type on every single day.",
      "He should tell her the practical answer is that she does not need another mechanical keyboard, but the wise answer is to help her choose in a way that does not accidentally create unnecessary tension at home.",
    ],
    medium: [
      "Ask which one she will actually use more.",
      "Say six is enough, but choose the pretty one.",
      "Say six is enough, but choose the better sounding one.",
      "Tell her to sell one before buying one.",
      "Ask whether this is a want or a need.",
      "Suggest waiting one week first.",
      "Pick the one she likes more.",
      "Tell her to follow her heart, but calmly.",
      "Ask which one sparks more joy.",
      "Say no first, then help anyway.",
    ],
    weak: [
      "Buy both and deal with it later.",
      "Pretend mechanical keyboards are an investment.",
      "Say the desk needs more keyboards.",
      "Start a keyboard orphanage.",
      "Tell her seven is a lucky number.",
      "Ask the keyboards what they think.",
    ],
  },
};

export const fallbackAnswers = [
  "Communicate honestly and keep the peace.",
  "Laugh it off and solve it together.",
  "Choose kindness first.",
  "Do the safer thing.",
  "Compromise a little.",
  "Pick peace over pride.",
  "Think long term.",
  "Stay calm and be smart.",
  "Say sorry quickly.",
  "Do not make it worse.",
];
